name: CI

on:
  pull_request:
  push:
    branches: [ master ]

env:
  CI_CHECK_FAIL: ssh2

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      
      - name: Push Docker Image
        run: echo 123
